= Configure Mule to Connect to the EU Control Plane
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To use Mule runtime engine within the EU Control Plane, you must redefine the configuration properties that enable Mule runtime engine to point to the EU Control Plane. You must also provide the client ID and client secret of the environment belonging to your organization.

By default, Mule runtime engine is configured to point to the US control plane. If you do not override these properties, the API gateway capability of Mule runtime engine is disabled in the EU Control Plane.

== Configuring Mule Runtime Engine

You can configure Mule runtime engine (Mule) using `wrapper.conf`, the command line, or CloudHub.

=== wrapper.conf

To configure Mule runtime engine using the `wrapper.conf` file, modify the following properties, replacing `<n>` with an integer value that is unique within `wrapper.conf`:

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<environment client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<environment client secret>
wrapper.java.additional.<n>=-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

=== Command Line

To configure Mule runtime engine from the command line, use the following options when starting Mule runtime engine. Note that `./` only applies to Unix environments.

----
./mule -M-Danypoint.platform.client_id=<environment client ID> -M-
Danypoint.platform.client_secret=<environment client secret> -M-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
-M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

=== CloudHub

When deploying to CloudHub, include the following properties in the Properties tab:

----
anypoint.platform.client_id=<environment client ID>
anypoint.platform.client_secret=<environment client secret>
anypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
anypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----


== See Also

* xref:index.adoc[EU Control Plane]
* xref:platform-access-eu.adoc[Access the EU Control Plane]
