= Configure Mule to Connect to the EU Control Plane
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To use Mule runtime engine within the EU Control Plane, you must redefine the configuration properties that enable Mule runtime engine to point to the EU Control Plane. You must also provide the client ID and client secret of the environment belonging to your organization.

By default, Mule runtime engine is configured to point to the US control plane. If you do not override these properties, the API Gateway capability of Mule runtime engine is disabled in the EU Control Plane.

The properties you must override depend on the version of Mule runtime engine you are using: Mule 4.0 or Mule 3.x.

== Configuring Mule 4.0

=== wrapper.conf

To configure Mule runtime engine using the `wrapper.conf` file, modify the following properties:

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<environment client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<environment client secret>
wrapper.java.additional.<n>=-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

In the previous example, replace `<n>` with an integer value that is unique within the `wrapper.conf` file.

=== Command Line

To configure Mule runtime engine from the command line, use the following options when starting Mule runtime engine. Note that `./` only applies to Unix environments.

----
./mule -M-Danypoint.platform.client_id=<environment client ID> -M-
Danypoint.platform.client_secret=<environment client secret> -M-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
-M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

=== CloudHub

When deploying to CloudHub, include the following properties in the Properties tab:

----
anypoint.platform.client_id=<environment client ID>
anypoint.platform.client_secret=<environment client secret>
anypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
anypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

== Configuring Mule 3.x

=== wrapper.conf

To configure `wrapper.conf` file, modify the following properties:

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<environment client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<environment client secret>
wrapper.java.additional.<n>=-Danypoint.platform.platform_base_uri=https://eu1.anypoint.mulesoft.com/apiplatform
wrapper.java.additional.<n>=-Danypoint.platform.coreservice_base_uri=https://eu1.anypoint.mulesoft.com/accounts
wrapper.java.additional.<n>=-Danypoint.platform.contracts_base_uri=https://eu1.anypoint.mulesoft.com/apigateway/ccs
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

In the previous example, replace `<n>` with an integer value that is unique within the `wrapper.conf` file.

=== Command Line

To configure Mule runtime engine from the command line, use the following options when starting Mule runtime engine. Note that `./` only applies to Unix environments.

----
./mule -M-Danypoint.platform.client_id=<org client ID> -M-
Danypoint.platform.client_secret=<org client secret> -M-Danypoint.platform.platform_base_uri=https://eu1.anypoint.mulesoft.com/apiplatform -M-Danypoint.platform.coreservice_base_uri=https://eu1.anypoint.mulesoft.com/accounts -M-Danypoint.platform.contracts_base_uri=https://eu1.anypoint.mulesoft.com/apigateway/ccs -M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

=== CloudHub

When deploying to CloudHub, you must add the following information and enable the autodiscovery feature in the Properties tab.

----
anypoint.platform.client_id=<environment client ID>
anypoint.platform.client_secret=<environment client secret>
anypoint.platform.platform_base_uri=https://eu1.anypoint.mulesoft.com/apiplatform
anypoint.platform.coreservice_base_uri=https://eu1.anypoint.mulesoft.com/accounts
anypoint.platform.contracts_base_uri=https://eu1.anypoint.mulesoft.com/apigateway/ccs
anypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

== See Also

* xref:index.adoc[EU Control Plane]
* xref:platform-access-eu.adoc[To Access the EU Control Plane]
